spring:
  application:
    name: 06-MS-Config-Server-App
  cloud:
    config:
      server:
        git:
          uri: https://github.com/surajphunde/surajphunde-config   
          default-label: main   # <-- FIXED: must be indented properly
          clone-on-start: true # git hub app.yml property fetch

server:
  port: 9090
