spring:
  application:
    name: greet-api

  boot:
    admin:
      client:
        url: http://localhost:9090

server:
  port: 2222

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
