server:
  port: 9090

spring:
  application:
    name: resilience4j-demo

management:
  endpoints:
    web:
      exposure:
        include: "*"  # exposes all actuator endpoints
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      suraj:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
